name: Build

on:
  push:
    branches: [ main ]
    tags: [ '*' ]
  pull_request:
    branches: [ main ]


  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: montudor/action-zip@v1
      with:
        args: zip -qq -r aztube-extension.zip icons scripts styles index.html manifest.json
    - run: cp aztube-extension.zip aztube-extension.crx
    - uses: actions/upload-artifact@v3.1.0
      with:
        name: extension-m3
        path: aztube-extension.*
    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          aztube-extension.zip
          aztube-extension.crx
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: rm manifest.json && mv manifest-v2.json manifest.json
    - uses: montudor/action-zip@v1
      with:
        args: zip -qq -r aztube-extension.zip icons scripts styles index.html manifest.json
    - run: cp aztube-extension.zip aztube-extension.xpi
    - uses: trmcnvn/firefox-addon@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        uuid: '{55a5247f-9358-43d0-a43f-05a7a7fc8c2a}'
        xpi: aztube-extension.xpi
        manifest: manifest.json
        api-key: ${{ secrets.FIREFOX_API_KEY }}
        api-secret: ${{ secrets.FIREFOX_API_SECRET }}
    - uses: actions/upload-artifact@v3.1.0
      with:
        name: extension-m2
        path: aztube-extension.*
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: montudor/action-zip@v1
      with:
        args: zip -qq -r aztube-extension.zip icons scripts styles index.html manifest.json
    - run: mv aztube-extension.zip aztube-extension.crx
    - run: rm manifest.json && mv manifest-v2.json manifest.json
    - uses: montudor/action-zip@v1
      with:
        args: zip -qq -r aztube-extension.zip icons scripts styles index.html manifest.json
    - run: cp aztube-extension.zip aztube-extension.xpi
    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          aztube-extension.zip
          aztube-extension.crx
          aztube-extension.xpi

