name: Build

on:
  push:
    branches: [ main ]
    tags: [ '*' ]
  pull_request:
    branches: [ main ]


  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: montudor/action-zip@v1
      with:
        args: zip -qq -r aztube-extension.zip scripts styles index.html manifest.json
    - run: cp aztube-extension.zip aztube-extension.crx
    - uses: actions/upload-artifact@v3.1.0
      with:
        name: extension
        path: aztube-extension.*
    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          aztube-extension.zip
          aztube-extension.crx
    
