name: Build

on:
  push:
    branches: [ main ]
    tags: [ '*' ]
  pull_request:
    branches: [ main ]


  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: montudor/action-zip@v1
      with:
        args: zip -qq -r aztube-extension.zip scripts styles index.html manifest.json
    - run: cp aztube-extension.zip aztube-extension.crx
    - run: cp aztube-extension.zip aztube-extension.xpi
    - uses: actions/upload-artifact@v3.1.0
      with:
        name: extension
        path: aztube-extension.*
    - uses: trmcnvn/firefox-addon@v1
      with:
        # uuid is only necessary when updating an existing addon,
        # omitting it will create a new addon
        uuid: '{55a5247f-9358-43d0-a43f-05a7a7fc8c2a}'
        xpi: build/my-addon.xpi
        manifest: manifest.json
        api-key: ${{ secrets.FIREFOX_API_KEY }}
        api-secret: ${{ secrets.FIREFOX_API_SECRET }}
    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          aztube-extension.zip
          aztube-extension.crx
    
